apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
          name: api
          ports:
            - containerPort: 5566
              hostPort: 5566
              protocol: TCP
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: CELESTRACK_URL
              value: https://celestrak.org/NORAD/elements/
            - name: SPACETRACK_URL
              value: https://www.space-track.org
            - name: HOST
              value: "0.0.0.0"
            - name: SPACETRACK_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: spacetrack-crendentials
            - name: SPACETRACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: spacetrack-crendentials
      restartPolicy: Always
