services:
#  server:
#    build:
#      context: .
#      target: final
#    ports:
#      - 5566:5566
#      - 8080:8080
#
#    volumes:
#      - ./data.json:/bin/data.json
#

  nginx-cache:
    build:
      context: nginx-cache

    ports:
      - 9080:80
      - 9081:81
