services:
  nginx-cache:
    build:
      context: nginx-cache

    ports:
      - 9080:80
      - 9081:81
  api:
    image: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api:develop
    ports:
      - 5566:5566
      - 8080:8080
    env_file:
      - .env.docker