openapi: 3.0.2
info:
  title: Satellite Positions API
  description: Returns the positions of all satellites at a given time in JSON format
  version: 1.0.0

paths:
  /satellites:
    get:
      summary: Get all satellite positions at a given times in JSON format
      description: Returns the positions of all satellites at a given times in JSON format or the current time if no times are provided
      parameters:
        - name: times
          in: query
          description: Array of times in UTC to get satellite positions for
          required: false
          schema:
            type: array
            items:
              type: string
              format: date-time
            example: ["2021-01-01T12:00:00Z", "2021-01-01T12:30:00Z"]

      responses:
        200:
          description: Satellite positions returned in JSON format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Satellite'
        400:
          description: Bad request, please provide a valid times parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid times provided"
        500:
          description: Internal server error, unable to retrieve satellite positions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
components:
  schemas:
    SatellitePosition:
      type: object
      properties:
        lat:
          type: number
          format: decimal
          description: Latitude of the satellite
        lon:
          type: number
          format: decimal
          description: Longitude of the satellite
        altitude:
          type: number
          format: decimal
          description: Altitude of the satellite in meters

    Satellite:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the satellite
        positions:
          type: array
          items:
            $ref: '#/components/schemas/SatellitePosition'
          description: Array of positions of the satellite at the given times


    SatelliteDetail:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the satellite
        name:
          type: string
          description: Name of the satellite
        description:
          type: string
          description: Description of the satellite
        velocity:
          type: number
          format: decimal
          description: Velocity of the satellite in meters per second
        launchDate:
          type: string
          format: date-time
          description: Date the satellite was launched
