apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - api-deployment.yaml
  - api-service.yaml
  - nginx-cache-deployment.yaml
  - nginx-cache-service.yaml

images:
  - name: ghcr.io/tsukoyachi/react-flight-tracker-satellite/api
    newName: ghcr.io/tsukoyachi/react-flight-tracker-satellite/api
    newTag: v1.0.0
  - name: nginx-cache
    newName: ghcr.io/tsukoyachi/react-flight-tracker-satellite/nginx-cache
    newTag: v1.0.0


patches:
  - target:
      kind: Ingress
      name: react-flight-tracker-ingress
    path: ingress-patch.yaml