apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 56f3b903b8ac4d72060f2ea87c999e57b8e5734d
  - name: nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/cache
    newTag: 56f3b903b8ac4d72060f2ea87c999e57b8e5734d


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml