apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 8a098f08caabc017e2158a1abbfa994643d4674f
  - name: nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/cache
    newTag: 8a098f08caabc017e2158a1abbfa994643d4674f


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml