apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 1d22dc6f9906484d5b82229fcd92a3cfd62c88f6
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 1d22dc6f9906484d5b82229fcd92a3cfd62c88f6


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml