apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: e8e5416403df5fc2867010125d0cf2b0faaa0dff
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: e8e5416403df5fc2867010125d0cf2b0faaa0dff


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml