apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: dcfe1a17b31ecee81fe5063f95c841afa0b7b14c
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: dcfe1a17b31ecee81fe5063f95c841afa0b7b14c


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml