apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: a1b724d791d6e4eafb8c8102d01171b3d300855b
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: a1b724d791d6e4eafb8c8102d01171b3d300855b


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml