apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 80c1d12d4bac2b5be7adcec7b809b16eeedf2bc3
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 80c1d12d4bac2b5be7adcec7b809b16eeedf2bc3


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml