apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: eceb17b70a68a2e31b735cb34daa653c4f57de36
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: eceb17b70a68a2e31b735cb34daa653c4f57de36


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml