apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 2d61ac8689be8c73da6f9b3f9149ea81cf5069a9
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 2d61ac8689be8c73da6f9b3f9149ea81cf5069a9


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml