apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 70af593e39c7366d443962fe109165f8e0e799f8
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 70af593e39c7366d443962fe109165f8e0e799f8


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml