apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 9085dc190e7a2340f3134b9bcc670d1122b1dd8e
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 9085dc190e7a2340f3134b9bcc670d1122b1dd8e


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml