apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 022a45d2cc55361d33b5951aa5e125c1a5953fbd
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 022a45d2cc55361d33b5951aa5e125c1a5953fbd


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml