apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 1d463338abeeaabb4695cc136176d5d13657845f
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 1d463338abeeaabb4695cc136176d5d13657845f


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml