apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
    newTag: 58fe385c5306b7131d99eb4bfca7e0317f8446ce
  - name: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newName: ghcr.io/startupnationlabs/react-flight-tracker-satellite/nginx-cache
    newTag: 58fe385c5306b7131d99eb4bfca7e0317f8446ce


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml